In [1]:
import numpy as np
import torch

/opt/homebrew/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x = np.random.randint(0,20, (2,4,2))

In [3]:
x

array([[[15,  4],
        [11,  4],
        [11,  2],
        [17, 11]],

       [[15, 16],
        [10,  8],
        [ 8, 14],
        [ 3,  7]]])

In [4]:
np.s_[1 : 3, 5 : 11 : 2]

(slice(1, 3, None), slice(5, 11, 2))

In [5]:
np.nd_slice_to_indexes(np.s_[1 : 3, 5 : 11 : 2])

AttributeError: module 'numpy' has no attribute 'nd_slice_to_indexes'

In [6]:
x = torch.randint(0, 15, (2,4,2))

In [7]:
x[:, 1:4, :].shape

torch.Size([2, 3, 2])

In [8]:
x.stride(), x.shape


((8, 2, 1), torch.Size([2, 4, 2]))

In [16]:
x = torch.randint(0,15, (16,32,64,1))

In [17]:
strides = [1]
tmp_i = 1
for i in reversed(x.shape[1:]):
    tmp_i = tmp_i * i
    strides.insert(0, tmp_i)

In [18]:
strides

[2048, 64, 1, 1]

In [19]:
x.stride()

(2048, 64, 1, 1)

In [20]:
x.shape

torch.Size([16, 32, 64, 1])

In [21]:
x[0:5, 5:10, :, :]

tensor([[[[14],
          [12],
          [11],
          ...,
          [ 7],
          [ 7],
          [14]],

         [[10],
          [10],
          [ 0],
          ...,
          [14],
          [12],
          [ 1]],

         [[ 1],
          [ 0],
          [ 3],
          ...,
          [11],
          [ 8],
          [14]],

         [[ 5],
          [11],
          [12],
          ...,
          [ 4],
          [ 8],
          [ 2]],

         [[ 2],
          [ 0],
          [ 8],
          ...,
          [13],
          [13],
          [11]]],


        [[[10],
          [ 2],
          [ 0],
          ...,
          [ 7],
          [ 8],
          [ 2]],

         [[12],
          [14],
          [ 4],
          ...,
          [ 7],
          [ 3],
          [12]],

         [[ 7],
          [13],
          [12],
          ...,
          [ 2],
          [ 0],
          [ 7]],

         [[13],
          [14],
          [ 1],
          ...,
          [ 8],
          [12],

2048

In [23]:
torch.arange(5) + 2048

tensor([2048, 2049, 2050, 2051, 2052])

In [ ]:
torch.gather(x.flatten(), dim=0, index=)

In [32]:
np.ravel_multi_index((list(np.arange(0,5)),list( np.arange(5,10)), list(np.arange(64)),list( np.arange(1))), (16, 32, 64, 1))

ValueError: operands could not be broadcast together with shapes (5,) (5,) (64,) (1,) 

In [38]:
np.ix_(np.r_[0:5], np.r_[5:10], np.r_[0:64], np.r_[0:1])

(array([[[[0]]],
 
 
        [[[1]]],
 
 
        [[[2]]],
 
 
        [[[3]]],
 
 
        [[[4]]]]),
 array([[[[5]],
 
         [[6]],
 
         [[7]],
 
         [[8]],
 
         [[9]]]]),
 array([[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5],
          [ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
          [27],
          [28],
          [29],
          [30],
          [31],
          [32],
          [33],
          [34],
          [35],
          [36],
          [37],
          [38],
          [39],
          [40],
          [41],
          [42],
          [43],
          [44],
          [45],
          [46],
          [47],
          [48],
          [49],
      

In [40]:
idx = np.ravel_multi_index(multi_index=(np.ix_(np.r_[0:5], np.r_[5:10], np.r_[0:64], np.r_[0:1])), dims=(16,32,64,1))

In [48]:
torchidx = torch.from_numpy(idx.flatten())

In [50]:
torch.allclose(x[0:5, 5:10, :, :].flatten(), torch.gather(x.flatten(), dim=0, index=torchidx))

True

In [49]:
torch.gather(x.flatten(), dim=0, index=torchidx)

tensor([14, 12, 11,  ...,  7,  2,  8])

In [47]:
x.flatten().shape, torchidx.shape

(torch.Size([32768]), torch.Size([5, 5, 64, 1]))